# Generated by Django 6.0 on 2025-12-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('phone', models.IntegerField(max_length=50, verbose_name='phone')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
    ]
