# Generated by Django 6.0 on 2025-12-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_created_at_contact_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='phone'),
        ),
    ]
