# Generated by Django 6.0 on 2026-01-11 04:33

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=200, validators=[core.validators.validate_email], verbose_name='Email'),
        ),
    ]
